### ISSUE TITLE
conflation question

### ISSUE THREAD

**Issue by petercblack** [OvertureMaps/data#130]
Hi, take the below example of Bing (blue) and Overture (orange) buildings. In this case, why wouldn't the bing building in the center be included in the conflation since it doesn't intersect the Overture (presumably majority OSM, since it's downtown Dallas TX)? Wouldn't Overture want all buildings from Bing that don't fully intersect? Or am I misunderstanding the nature of the conflation? 
<img width="1491" alt="Screenshot 2024-03-07 at 5 58 21 PM" src="https://github.com/OvertureMaps/data/assets/46737499/3bfa7bb1-f65e-4738-b7eb-2f1e3d98f068">

**Comment by petercblack** [comment]
Finding this issue throughout when comparing to MS Bing data, even from last year. Seems like the conflation could be improved by fully determining any disjoint data from Bing.

**Comment by jenningsanderson** [comment]
Woah, that's quite the ML footprint in the center. Yes, if there is no corresponding OSM footprint, conflation should be choosing an ML footprint if present.

In this case, I think the ML building is being excluded from conflation due to the complexity and number of sharp angles present in the geometry. 

As we continue to improve the conflation logic, we will be sure to better document these types of filters and data improvements. 

On a final note — the best way to remedy this building is simply to add/fix the building in OSM  — do you have coordinates for this screenshot?

**Comment by Cj-Malone** [comment]
> On a final note — the best way to remedy this building is simply to add/fix the building in OSM — do you have coordinates for this screenshot?

https://www.openstreetmap.org/way/1258797702

**Comment by petercblack** [comment]
Thanks Jennings. I think the example here is probably a poor one. Take the example below. Overture is in a translucent light blue, Bing in light orange. Where they overlap is in green. For clarity's sake, is the conflation algo not picking up these Bing ML buildings in North Philly (40.028243,-75.128857) due to the complexity of the polygons? There are millions of these examples, and just want to be certain that the rules that have been chosen is the reason these aren't included in Overture. 
<img width="1231" alt="Screenshot 2024-04-02 at 11 54 43 AM" src="https://github.com/OvertureMaps/data/assets/46737499/72efcff6-0cc0-45b0-8e83-3383ad856d36">

**Comment by jenningsanderson** [comment]
Thanks for pointing this out — what's also odd to me here is that it looks like the OSM basemap has the buildings. This is certainly an odd case. I will look further into this.
