### ISSUE TITLE
Georgia and French Guiana are missing from https://explore.overturemaps.org/#6.31/3.753/-52.214

### ISSUE THREAD

**Issue by danabauer** [OvertureMaps/data#190]
Georgia and French Guiana are missing from the explore site. https://explore.overturemaps.org/#6.31/3.753/-52.214
French Guiana is in the July release data with division_area id `085d05a27fffffff017bf5d30ba05377`  

Any thoughts why it and Georgia might be missing from the map? Is this a data issue or a tiling issue?

**Comment by Bonkles** [comment]
From the explorer side, it does indeed look like the French Guiana division is missing from the PMTiles- it doesn't show up under debug inspection of the data we get back at that location.

I can repro the same issue using the PMTiles functionality of Rapid. 

 So, it's looking like either this feature is dropped from the tileset somehow. It doesn't look like a styling issue.

**Comment by bdon** [comment]
It's likely being dropped from the tileset somehow - checking now.

**Comment by bdon** [comment]
What I suspect is going on:

The logic for which divisions appear in the tileset at what zoom level is [this](https://github.com/OvertureMaps/overture-tiles/blob/main/scripts/2024-07-22/divisions.sh#L16): 

```
CASE WHEN subtype = 'country' THEN 0 WHEN subtype = 'region' THEN 4 WHEN subtype = 'county' THEN 8 ELSE 10 END
```

In the case of Georgia, the polygon and point label from `division_area` and `division` are there, respectively, in the Explorer. But no sub-divisions of Georgia are rendered compared to its neighbors, making it look missing, because the neighbors have >= 2 overlapping shades of purple:

<img width="635" alt="Screenshot 2024-07-27 at 00 32 33" src="https://github.com/user-attachments/assets/718defc1-9b56-4be9-bf9a-08db26159422">

Is it possible that Georgia's admin subdivisions are classified differently compared to other admin0s?

In the case of French Guiana it likely also isn't passing the SQL logic above because its attributes in the dataset are not `country`. In this case French Guiana is a `dependency` so it doesn't show up until z10.

**Comment by stepps00** [comment]
> Is it possible that Georgia's admin subdivisions are classified differently compared to other admin0s?

```
SELECT distinct(subtype)
FROM read_parquet('s3://overturemaps-us-west-2/release/2024-07-22.0/theme=divisions/type=*/*', filename=true, hive_partitioning=1)
WHERE country = 'GE' ;
```

results in 

```
┌──────────────┐
│   subtype    │
│   varchar    │
├──────────────┤
│ neighborhood │
│ country      │
│ locality     │
│ microhood    │
└──────────────┘
```

So yes, subdivisions are classified differently in Georgia. There are no region, county, or localadmin subtypes present.

**Comment by bdon** [comment]
For Georgia, can we expect there to be `regions` in a future release?

**Comment by stepps00** [comment]
I imagine so, to either represent [autonomous republics](https://en.wikipedia.org/wiki/Administrative_divisions_of_Georgia_(country)#Autonomous_republics) or the [the region](https://en.wikipedia.org/wiki/Administrative_divisions_of_Georgia_(country)#Regions) division in Georgia.

cc @DavidKarlas do you have any context here? I see references to Georgia's admin_level 8 in the subtype mappings, but guessing the autonomous republics are causing some odd subtype hierarchy in the country.

**Comment by FlorisCalkoen** [comment]
I just noticed that the Shetland islands and Svalbard are missing from the July release as well. The issue becomes clear when filtering the division_area type on subtype == "country". At regional level (subtype=="region") the data is available, plus contains a country attribute (alpha-2 code)

**Comment by bdon** [comment]
@FlorisCalkoen Svalbard is `subtype=dependency` and should appear on the explore site now: 

https://explore.overturemaps.org/#3.32/79.19/17.4

Are you observing the Shetland Islands are missing from the GeoParquet data, or just the Explore site?

**Comment by bdon** [comment]
Since `subtype=dependency` is now in the Explore site I'm going to close this issue in favor of #192
