### ISSUE TITLE
postalCode is always null in 2023-10-19-alpha.0

### ISSUE THREAD

**Issue by hroongtatrip** [OvertureMaps/data#88]
Previousaly in  July data version postCode was not empty for most places in US.
However it is null for alll of them. Please help. 

Some examples-

[{freeform=9 Crystal St, locality=East Stroudsburg, postcode=null, region=PA, country=US}] | 118493168796309
[{freeform=5825 Spring Mountain Rd, locality=Las Vegas, postcode=null, region=NV, country=US}] | 102597961280184 
[{freeform=501 W 51st St, locality=New York, postcode=null, region=NY, country=US}] | 127960346496

**Comment by jwass** [comment]
Hi @hroongtatrip - This is now fixed in the (just released!) November data. 

I made a table on the data and ran this query to verify that most entries now have a postcode. I'll close this but feel free to reach out if there are any other issues.

<img width="872" alt="Screenshot 2023-11-14 at 9 54 19 AM" src="https://github.com/OvertureMaps/data/assets/1214350/bf655f3f-ec86-4bb5-b230-32af8d1abeb5">

**Comment by hroongtatrip** [comment]
Thanks @jwass . While I see the postal code now I see lot more rows for  "addresses" columns has empty array as compared to 2023_10_19_alpha.0

Example-
`select * from overture_2023_10_19_alpha_0 where theme='places' 
and id = '333229687260011'
limit 10


select * from overture_2023_11_14_alpha_0 where theme='places' 
and id = '333229687260011' 
limit 10`

First one from the prev version has addresses fielld of "[{freeform=null, locality=Grentheville, postcode=null, region=null, country=FR}]"

**Comment by jwass** [comment]
Hi @hroongtatrip. This is intentional but could be something to revisit. The underlying reasoning behind this is that the schema requires freeform to be present in every address entry. That's from https://github.com/OvertureMaps/schema/blob/main/schema/defs.yaml#L234. 

I think there's potentially the question of whether this requirement is the right thing to do and whether we can allow freeform to be null and just populate the rest of the fields if known. What do you think? You could open a discussion to raise with the team if that should change.
