### ISSUE TITLE
Import OpenStreetMap places

### ISSUE THREAD

**Issue by upintheairsheep** [OvertureMaps/data#96]
Can you import all missing OpenStreetMap places into this sprawling dataset please, and use some deduplication technique, and has an upper hand on including parking lots, restrooms, ATMs, and drinking water fountains

**Comment by jwass** [comment]
Hi @upintheairsheep. For the time being we have decided not to conflate OSM places with our own generated dataset. This could change in the future but it's not planned currently.

**Comment by upintheairsheep** [comment]
> Hi @upintheairsheep. For the time being we have decided not to conflate OSM places with our own generated dataset. This could change in the future but it's not planned currently.

OSM has minor amenities such as drinking water fountains, restrooms, parking lots, public telephones/Emegency telephones, vending machines, and ATMs

**Comment by sfkeller** [comment]
> Hi @upintheairsheep. For the time being we have decided not to conflate OSM places with our own generated dataset. This could change in the future but it's not planned currently.

@jwass: Any explanations for this decision?

As @upintheairsheep argued, OSM has the upper hand on many POI and "place" entitie classes. 

Is it that Overture Places is the last resort to be attributed to CDLA Permissive 2.0 among all the other Overture data? https://docs.overturemaps.org/attribution/

**Comment by Kind-Dog** [comment]
> > Hi @upintheairsheep. For the time being we have decided not to conflate OSM places with our own generated dataset. This could change in the future but it's not planned currently.
> 
> @jwass: Any explanations for this decision?

We don't want Places under the ODbL.

> Is it that Overture Places is the last resort to be attributed to CDLA Permissive 2.0 among all the other Overture data? https://docs.overturemaps.org/attribution/

Overture Places is currently the only Overture dataset not to contain OSM data and so it available CDLA. The other datasets quality reflect the quality of OSM.

**Comment by jwass** [comment]
@sfkeller You're right - We are currently keeping the Overture Places as CDLAv2 as these are contributed from outside of OSM and by member organizations. While we don't want to include ODbL places in Overture's Places dataset, Overture Places are able to be contributed into OSM by the OSM community if anyone wanted.

**Comment by sfkeller** [comment]
Okay thx. 

But since I have the impression that OSM / ODbL “places” are of better quality than most places contributed from outside OSM, wouldn't it make more sense to integrate these places into OSM with the appropriate care in the first place, and then re-import them? Given the amount of money invested in Overture Maps, I hope you find a way to do this. 

Or have you ditched the earlier Daylight process with the “find-fix-import loop”?

**Comment by mprioleau** [comment]
@sfkeller We licensed the Overture places data under the CDLA Permissive v2 licenses so that it can be used with other places datasets. If it carried the ODbL, it could only be used with other ODbL data (which is mainly OSM). It could not be used with other commercial data or other permissively licensed open data. 
Most users of Places data combine data from various sources to get to the coverage they want. We anticipate that users will combine Overture Places data with other sources, including commercially licensed data until a time when the open data is sufficient on its own. The CDLA license allows them to do that.
The Overture data can be added to OSM if a community member chooses to do so. However, once it is in OSM (and is ODbL), we won't bring it back into Overture for the reasons mentioned above.

**Comment by sfkeller** [comment]
Understood. 

But first, I would like to emphasize that ODbL does allow many use cases together with commercial licenses.

Secondly, what about the idea that Overture Maps aligns its processes in such a way that it, for example, synchronizes its Places with OSM and integrates fixes into OSM (similar to the former Daylight process) - and thus uses the quality of OSM Places while giving something back to OSM itself?

**Comment by wiseHolmes** [comment]
> Overture Places is currently the only Overture dataset not to contain OSM data and so it available CDLA. The other datasets quality reflect the quality of OSM.

... Overture Places is the worst Overture dataset.

> Overture Places are able to be contributed into OSM by the OSM community if anyone wanted.

This issue with OSM using Overture Places is the quality, not the license. Using Overture Places in OSM would make OSM worse, not better. Overture Places is full of old POIs. Bad categorisation. SEO spam. Weird airports. And "confidence" that may as well be random. I hope Overture Places gets some major improvements because for the last 11 months it has been unusable.

**Comment by Kind-Dog** [comment]
The Daylight pipeline didn't allow us to gain enough market share and left us with a big dependency on OSM. Overture will not be moving backwards, we will be advocating for the use of our schema and moving away from copyleft data where viable.

**Comment by sfkeller** [comment]
@Kind-Dog Your answer confuses me: “market share”? As I said: ODbL is not an obstacle to commercial re-licensing (if Overture wants). And deriving a “Places” Overture Maps schema from the higher quality OSM data works (anytime for everyone).

**Comment by jwass** [comment]
@sfkeller Kind-Dog is not a member of Overture - as evidenced by lack of a "Member" badge next to their comments. They don't represent the project or its opinions.

**Comment by mprioleau** [comment]
@sfkeller Thanks for the comments. Hopefully this can clarify:

> I would like to emphasize that ODbL does allow many use cases together with commercial licenses.

Agree, but only if the combined data sets are independent/collective and not derivative. For example, you could not use an ODbL dataset and then supplement it with a non-ODbL dataset to build out coverage. That's a pretty typical model for users building out a local search product. Permissive licenses (like CDLA) allow that use case.

> what about the idea that Overture Maps aligns its processes in such a way that it, for example, synchronizes its Places with OSM and integrates fixes into OSM (similar to the former Daylight process

In data themes where we use OSM, we try to leverage the OSM editing pipelines and push changes into those pipelines. Since we don't use OSM data in Places, that doesn't work.

**Comment by sfkeller** [comment]
Thanks. It still seems to me that your decision not to include OSM data in Places for the time being is not primarily based on arguments like legal use cases or data quality. I hope you will reconsider this decision and find a cooperative solution in Places. Together - Overture and OSM - we would all be stronger.

**Comment by upintheairsheep** [comment]
> Thanks. It still seems to me that your decision not to include OSM data in Places for the time being is not primarily based on arguments like legal use cases or data quality. I hope you will reconsider this decision and find a cooperative solution in Places. Together - Overture and OSM - we would all be stronger.

It would be best to make a (Python?) script to import all OSM places into the overture dataset if they respect OSM’s license, solving legal issues. Quality issues may be problematic, although you can lower the weight of OSM places and data.

**Comment by upintheairsheep** [comment]
> > Overture Places is currently the only Overture dataset not to contain OSM data and so it available CDLA. The other datasets quality reflect the quality of OSM.
> 
> ... Overture Places is the worst Overture dataset.
> 
> > Overture Places are able to be contributed into OSM by the OSM community if anyone wanted.
> 
> This issue with OSM using Overture Places is the quality, not the license. Using Overture Places in OSM would make OSM worse, not better. Overture Places is full of old POIs, awful coordinates, bad categorisation, SEO spam, weird airports, duplicates and "confidence" that may as well be random. I hope Overture Places gets some major improvements because for the last 11 months it has been unusable.

I believe that OSM should not import Overture due to there being tons of janky data, and the placement of the pins would make OSM look horrible.
